@RoleBasedAuthenticationApi_HostAddress =  https://localhost:7226

### Register a new user
POST {{RoleBasedAuthenticationApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "string",
  "email": "user@example.com",
  "password": "string"
}

### Login
POST {{RoleBasedAuthenticationApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "string"
}

### Access Admin Resource
GET {{RoleBasedAuthenticationApi_HostAddress}}/api/users/
Authorization: Bearer YOUR_ACCESS_TOKEN