using System.ComponentModel.DataAnnotations.Schema;

namespace RoleBasedAuthenticationApi.Models
{
    public class RefreshToken
    {
        //PK: GUID will be generated by DB
        public Guid Id { get; set; }

        //FK to AspNetUsers.Id column in AspNetUsers table
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public string TokenHash { get; set; } //use hash token and index it
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset ExpiredAt { get; set; }

        //Rotation and Revocation
        public bool Revoked { get; set; }
        public DateTimeOffset RevokedAt { get; set; }
        public string? RevokedByIP { get; set; }

        //Link to the token replacement 
        public RefreshToken? ReplaceByToken {  get; set; }

        public Guid? ReplaceByTokenId { get; set; }

        //computed property
        [NotMapped]
        public bool IsActive => !Revoked && DateTimeOffset.UtcNow < ExpiredAt;
    }
}
